In [1]:
import torch



In [2]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
a.shape

torch.Size([2, 3])

In [4]:

a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
print(a.sum(0))
print(a.sum(0).shape)

tensor([5, 7, 9])
torch.Size([3])


In [8]:
print(a.sum(1))
print(a.sum(1).shape)

tensor([ 6, 15])
torch.Size([2])
