In [2]:
import torch



In [2]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
a.shape

torch.Size([2, 3])

In [4]:

a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
print(a.sum(0))
print(a.sum(0).shape)

tensor([5, 7, 9])
torch.Size([3])


In [8]:
print(a.sum(1))
print(a.sum(1).shape)

tensor([ 6, 15])
torch.Size([2])


In [11]:

# sigmoid test
x = torch.tensor([0.5, 1.0, 2.0], requires_grad=True)
out = torch.sigmoid(x)
print("output: ", out)
out.backward(torch.ones_like(out))
print("grad: ", x.grad)



output:  tensor([0.6225, 0.7311, 0.8808], grad_fn=<SigmoidBackward0>)
grad:  tensor([0.2350, 0.1966, 0.1050])
